spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  redis:
    host: localhost
    port: 6379

  kafka:
    properties:
      security.protocol:
        sasl.mechanism:
      consumer:
        properties.spring.json.trusted.packages: "*"
        bootstrap-servers: 127.0.0.1:9092
        group-id: notification
        auto-offset-reset: latest
        key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      listener:
        ack-mode: MANUAL
      producer:
        bootstrap-servers: 127.0.0.1:9092
        key-deserializer: org.apache.kafka.common.serialization.IntegerSerializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties.enable.idempotence: false




  datasource:
    hikari:
      maximum-pool-size: 4

    url: jdbc:mysql://127.0.0.1:3306/FFSNS
    username: root
    password: dkdldb12
    driver-class-name: com.mysql.cj.jdbc.Driver




jwt:
  secret-key: kimtaedong_FFSNS_project_2023_secret_key_test_token_secret_key_aaaaaaaaaaa

  token:
    expired-time-ms: 2592000000




